name: ask cli

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: change ownership
        run: |
          sed -i "s/LAMBDA_ARN/${{ secrets.LAMBDA_ARN}}/" skill-package/skill.json
          chmod -R 666 .
      - name: Alexa ASK AWS CLI Deploy
        # uses: xavidop/alexa-ask-aws-cli-docker@cc0039b7d4e650d4410584f1c616c5f529cbd906
        uses: xavidop/alexa-ask-aws-cli-docker@v1.0.6
        id: ask
        env:
          ASK_ACCESS_TOKEN: ${{ secrets.ASK_ACCESS_TOKEN }}
          ASK_REFRESH_TOKEN: ${{ secrets.ASK_REFRESH_TOKEN }}
          ASK_VENDOR_ID: ${{ secrets.ASK_VENDOR_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SKILL_ID: ${{ secrets.SKILL_ID }}
        with:
          command: 'cat skill-package/skill.json'
      - name: Get output
        run: echo "The result was ${{ steps.ask.outputs.result }}"
