name: ask cli

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Alexa ASK AWS CLI Action
        # You may pin to the exact commit or the version.
        # uses: xavidop/alexa-ask-aws-cli-docker@cc0039b7d4e650d4410584f1c616c5f529cbd906
        uses: xavidop/alexa-ask-aws-cli-docker@v1.0.6
        with:
          # Command to execute
          command: ask --version

